#!/bin/bash

function load {
  if [ -f $1 ]; then
     source $1
  fi
}

load ~/.bashrc
load ~/.bkup/dotfiles/bashrc/main.bash
load ~/.bkup/dotfiles/bashrc/$profile_name.bash
load ~/.bkup/dotfiles/bashrc/$os.bash
